# Generated by Django 2.2 on 2019-04-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=45, null=True, verbose_name='City')),
                ('zip', models.CharField(max_length=45, null=True, verbose_name='ZIP')),
                ('country', models.CharField(blank=True, max_length=45, null=True, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ('name',),
            },
        ),
    ]
