# Generated by Django 2.2 on 2019-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20190419_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hours',
            field=models.SmallIntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Salary/h'),
        ),
    ]
