# Generated by Django 2.2 on 2019-04-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='professionality',
            field=models.SmallIntegerField(choices=[(0, 'Trainee'), (1, 'Junior'), (2, 'Medior'), (3, 'Senior'), (4, 'Lead')], default=0, verbose_name='Professionality'),
        ),
    ]
