# Generated by Django 2.2 on 2019-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_professionality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='professionality',
            field=models.SmallIntegerField(choices=[(0, 'Trainee'), (1, 'Junior'), (2, 'Medior'), (3, 'Senior'), (4, 'Lead'), (5, 'Manager')], default=0, verbose_name='Professionality'),
        ),
    ]
