# Generated by Django 2.2 on 2019-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190418_1814'),
        ('employees', '0005_employee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobs',
            field=models.ManyToManyField(related_name='employees', to='restaurants.Restaurant', verbose_name='Jobs'),
        ),
    ]
