# Generated by Django 2.2 on 2019-04-19 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20190418_1814'),
        ('employees', '0006_employee_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='jobs',
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True, verbose_name='Name')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Salary')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employees.Employee')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='restaurants.Restaurant')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
