# Generated by Django 2.2 on 2019-04-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20190419_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
